### ISSUE TITLE
update-icon-cache for all themes called after installing icons in one location

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#50]
Hi,

Yesterday I ran the autovale-generated CMake for my app within a prestine Fedora 22 vm install and noticed the icons not showing up. An simple update-icon-cache command was able to solve that. Apparently the install script did not run the command at the right time.

So after investigating when exacltly when the update command was called, I found the calls for *all themes* in one specific (seemingly random) location: /data/icons/hicolor/22x22/CMakeLists.txt (see contents below this message)

I suppose this is the cause of the problem, the update command seems to be called after having installed just a few icons of one theme, while other icons have yet to be installed...

If you need to do some deeper analysis I can e-mail you the full project source.

```
### CMakeLists automatically created with AutoVala
### Do not edit

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connected.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-1.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-2.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-3.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-disconnected.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/apps/)
IF( NOT (${ICON_UPDATE} STREQUAL "OFF" ))
	install (CODE "execute_process ( COMMAND /usr/bin/gtk-update-icon-cache-3.0 -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/gnome )" )
	install (CODE "execute_process ( COMMAND /usr/bin/gtk-update-icon-cache-3.0 -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor )" )
	install (CODE "execute_process ( COMMAND /usr/bin/gtk-update-icon-cache-3.0 -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/ubuntu-mono-dark )" )
	install (CODE "execute_process ( COMMAND /usr/bin/gtk-update-icon-cache-3.0 -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/ubuntu-mono-light )" )
ENDIF()
```

**Comment by ztefn** [comment]
Hmm... this could also be a more basic problem. After some further investigating I found out that */usr/bin/gtk-update-icon-cache-3.0* command isn't present in Fedora 22, only */usr/bin/gtk-update-icon-cache*, without *-3.0*. What's the difference and is -3.0 really necessary?

**Comment by ztefn** [comment]
Apparently, the un-suffixed (without -3.0) should indeed be used instead: https://mail.gnome.org/archives/commits-list/2011-January/msg00799.html

**Comment by ztefn** [comment]
Okay, now tested again after having changed /usr/bin/gtk-update-icon-cache-3.0 into /usr/bin/gtk-update-icon-cache in the CMakeLists.txt file, I can also confirm my original report. When running make install I now see 2 (would have expected 4 though) icon-theme-update calls immediately after the first few icons --the 22px ones from hicolor-- are installed. This means only the 22px icons are cached, resulting in blurry icons in the GNOME shell.

So I'm affraid this means there two bugs to solve. The first is easy, just change *gtk-update-icon-cache-3.0* to *gtk-update-icon-cache*. The second one is to make these commands being called after all icons have been installed (at least for each seperate icon theme).

**Comment by rastersoft** [comment]
Hi. Thanks for your bug reports. Unfortunately, this week I have too much work (the-one-that-pays-the-bills, you know). I hope to be able to fix this next week.

**Comment by rastersoft** [comment]
I think I have fixed it (both bugs). Can you test it? It is in master.

**Comment by ztefn** [comment]
Hi, I've pulled the code from master on my build environment and I can see the script for the update-icon-cache command has been updated, so that looks good (though I haven't tested on Fedora 22 yet).

However, as you can see below all update commands still appear in the first (hicolor/22x22) folder:

```
### CMakeLists automatically created with AutoVala
### Do not edit

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connected.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-1.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-2.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-connecting-3.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp-disconnected.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/status/)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/myapp.png DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor/22x22/apps/)
if( NOT (${ICON_UPDATE} STREQUAL "OFF" ))
	find_program ( GTK_UPDATE_ICON_CACHE NAMES gtk-update-icon-cache.3.0 gtk-update-icon-cache )
	install (CODE "execute_process ( COMMAND ${GTK_UPDATE_ICON_CACHE} -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/Adwaita )" )
	install (CODE "execute_process ( COMMAND ${GTK_UPDATE_ICON_CACHE} -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/hicolor )" )
	install (CODE "execute_process ( COMMAND ${GTK_UPDATE_ICON_CACHE} -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/ubuntu-mono-dark )" )
	install (CODE "execute_process ( COMMAND ${GTK_UPDATE_ICON_CACHE} -t ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATAROOTDIR}/icons/ubuntu-mono-light )" )
ENDIF()
```

And the execution order appears the same too:
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/bin/myapp
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connected.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-1.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-2.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-3.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-disconnected.png
-- Installing: /usr/share/icons/hicolor/22x22/apps/myapp.png
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
-- Installing: /usr/share/icons/hicolor/32x32/apps/myapp.png
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connected.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-1.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-2.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-3.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-disconnected.svg
etc...
```

So I don't think this is gonna work, but I can test it further on my Fedora 22 vm if you like.

**Comment by rastersoft** [comment]
Ok, but at least the binary works fine, doesn't it?

I'll try to fix it again.

**Comment by ztefn** [comment]
Hi, tested on Fedora 22 now and I can confirm the "correct" update-icon-cache command is found and executed: the hicolor/22x22 icon is visible after installation. As expected all other icons are not cached and don't show up yet.

**Comment by rastersoft** [comment]
Ok, I think it should work fine now.

**Comment by ztefn** [comment]
Nope, unfortunately still the exact same result. Here's the full make install output on the Fedora 22 vm:
```
[ztefn@localhost build]$ sudo make install
[100%] Built target myapp
[100%] Built target i18n
Install the project...
-- Install configuration: ""
-- Installing: /usr/bin/myapp
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connected.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-1.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-2.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-connecting-3.png
-- Installing: /usr/share/icons/hicolor/22x22/status/myapp-disconnected.png
-- Installing: /usr/share/icons/hicolor/22x22/apps/myapp.png
gtk-update-icon-cache: Cache file created successfully.
-- Installing: /usr/share/icons/hicolor/32x32/apps/myapp.png
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connected.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-1.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-2.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-connecting-3.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/24/myapp-disconnected.svg
-- Installing: /usr/share/locale/cs/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/pl/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/fr/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/de/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/ja/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/pt_BR/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/id/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/es/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/ru/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/tr/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/ast/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/nl/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/uk/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/sk/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/it/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/kk/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/bg/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/locale/sv/LC_MESSAGES/myapp.mo
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-connected.png
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-connecting-1.png
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-connecting-2.png
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-connecting-3.png
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-disconnected.png
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-error.svg
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-offline.svg
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-online-relayed.svg
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-online.svg
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-unapproved.svg
-- Installing: /usr/share/icons/hicolor/24x24/status/myapp-node-unreachable.svg
-- Installing: /usr/share/icons/hicolor/24x24/apps/myapp.png
-- Installing: /usr/share/icons/Adwaita/scalable/status/myapp-connected-symbolic.svg
-- Installing: /usr/share/icons/Adwaita/scalable/status/myapp-connecting-1-symbolic.svg
-- Installing: /usr/share/icons/Adwaita/scalable/status/myapp-connecting-2-symbolic.svg
-- Installing: /usr/share/icons/Adwaita/scalable/status/myapp-connecting-3-symbolic.svg
-- Installing: /usr/share/icons/Adwaita/scalable/status/myapp-disconnected-symbolic.svg
-- Installing: /usr/share/icons/Adwaita/scalable/apps/myapp-symbolic.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-connected.png
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-connecting-1.png
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-connecting-2.png
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-connecting-3.png
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-disconnected.png
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-error.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-offline.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-online-relayed.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-online.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-unapproved.svg
-- Installing: /usr/share/icons/hicolor/16x16/status/myapp-node-unreachable.svg
-- Installing: /usr/share/icons/hicolor/16x16/apps/myapp.png
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/22/myapp-connected.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/22/myapp-connecting-1.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/22/myapp-connecting-2.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/22/myapp-connecting-3.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/22/myapp-disconnected.svg
-- Up-to-date: /usr/share/applications/myapp.desktop
-- Up-to-date: /etc/xdg/autostart/myapp-autostart.desktop
-- Up-to-date: /usr/share/glib-2.0/schemas/myapp.gschema.xml
-- Compiling GSettings schemas
-- Installing: /usr/share/icons/hicolor/48x48/status/myapp-connected.png
-- Installing: /usr/share/icons/hicolor/48x48/status/myapp-connecting-1.png
-- Installing: /usr/share/icons/hicolor/48x48/status/myapp-connecting-2.png
-- Installing: /usr/share/icons/hicolor/48x48/status/myapp-connecting-3.png
-- Installing: /usr/share/icons/hicolor/48x48/status/myapp-disconnected.png
-- Installing: /usr/share/icons/hicolor/48x48/apps/myapp.png
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/24/myapp-connected.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/24/myapp-connecting-1.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/24/myapp-connecting-2.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/24/myapp-connecting-3.svg
-- Installing: /usr/share/icons/ubuntu-mono-dark/status/24/myapp-disconnected.svg
-- Installing: /usr/share/icons/hicolor/256x256/apps/myapp.png
-- Installing: /usr/share/icons/ubuntu-mono-light/status/22/myapp-connected.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/22/myapp-connecting-1.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/22/myapp-connecting-2.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/22/myapp-connecting-3.svg
-- Installing: /usr/share/icons/ubuntu-mono-light/status/22/myapp-disconnected.svg
```
As you can see gtk-update-icon-cache is still called directly after installation of the hicolor/22x22 icons.

**Comment by rastersoft** [comment]
Ok, now it works.

**Comment by rastersoft** [comment]
Try it now, please. I made some changes and now it is better (it only updates the themes modified in each CMakeLists file, not all modified themes in all CMakeLists files).

**Comment by ztefn** [comment]
I just gave it a test. Didn't work yet because of the sequential calls for the same theme (with little time in between), making it think the cache was already up-to-date after the first call. But you could easily fix this by adding the **-t** option to the gtk-update-icon-cache command to force each update.

**Comment by rastersoft** [comment]
Mmm... It already have the -t option...

**Comment by rastersoft** [comment]
It is -f :) Added.

**Comment by rastersoft** [comment]
Please, check it, to close this.

**Comment by ztefn** [comment]
Tested, icon installation works like a champ now! Thanks again for your time and efforts!
